import {
  definePrototypeDataContract,
  type EntitySpec,
  type FieldSpec,
  type RelationSpec,
  type TechnicalValidation,
} from "./data-contract-schema";

/**
 * Fuente de verdad de los datos usados por el prototipo.
 *
 * El designer describe el producto en lenguaje natural; el agente mantiene este
 * contrato y ejecuta `pnpm check:data-contract` antes de implementar la UI.
 *
 * Fase 1 del build de Desk ReS: cubre los datos de **lectura** que la lista de
 * casos y la ficha (`CasoCard`) necesitan mostrar. Los campos que solo se usan
 * dentro de un diálogo de gestión (editables) se agregan cuando se construye
 * ese diálogo — ver readme-logica-res.md y ai/PROJECT-CONTEXT.md.
 */

// El proyecto todavía no tiene backend (ver readme-logica-res.md §3 y §10):
// todo dato depende de una definición técnica pendiente hasta que TI la
// confirme, así que casi todos los campos quedan pendingTi con esa nota.
const pendingBackend = (note: string): TechnicalValidation => ({
  status: "pendingTi",
  note,
});

const NOTE_SIN_BACKEND = "Sin backend real todavía: falta definir tabla y persistencia (RLS).";
const NOTE_SCRAPER =
  "Hoy se ingresa manualmente; en producción vendría de un scraper del CRM de ventas.";
const NOTE_APIO = "Hoy es mock; en producción se crea vía API de Apio.";

const lexyField = (
  field: Omit<FieldSpec, "origin" | "source" | "dataClassification" | "technicalValidation"> & {
    sensitive?: boolean;
    note?: string;
  },
): FieldSpec => {
  const { sensitive, note, ...rest } = field;
  return {
    ...rest,
    origin: "lexyConfirmed",
    source: { kind: "unknown" },
    dataClassification: sensitive ? "sensitive" : "internal",
    technicalValidation: pendingBackend(note ?? NOTE_SIN_BACKEND),
  };
};

const usedInDesk = ["Lista de casos", "Tarjeta de caso"];

const caso: EntitySpec = {
  id: "caso",
  productDescription: "Un caso de reevaluación de servicio en curso en el Desk ReS.",
  roleInExperience: "Entidad central: cada tarjeta de la lista representa un caso.",
  usedIn: usedInDesk,
  origin: "lexyConfirmed",
  source: { kind: "unknown" },
  dataClassification: "internal",
  technicalValidation: pendingBackend(NOTE_SIN_BACKEND),
  fields: {
    id: lexyField({
      id: "id",
      productDescription: "Identificador del caso.",
      dataType: "identifier",
      required: true,
      usage: { visible: false, editable: false, calculated: false, technical: true },
      usedIn: usedInDesk,
    }),
    tipoCaso: lexyField({
      id: "tipoCaso",
      productDescription: "Naturaleza del caso: qué tipo de reevaluación es.",
      dataType: "enum",
      enumValues: ["reevaluacion", "reembolso", "modificacion-contrato", "derivacion"],
      required: true,
      usage: {
        visible: true,
        editable: false,
        calculated: false,
        technical: false,
        filterable: true,
      },
      usedIn: [...usedInDesk, "Filtro por tipo"],
    }),
    estadoProceso: lexyField({
      id: "estadoProceso",
      productDescription: "En qué tab vive el caso y qué acciones tiene disponibles.",
      dataType: "enum",
      enumValues: ["por-evaluar", "en-evaluacion", "resuelto"],
      required: true,
      usage: {
        visible: true,
        editable: false,
        calculated: false,
        technical: false,
        filterable: true,
      },
      usedIn: [...usedInDesk, "Tabs En evaluación / Resueltos"],
    }),
    pasoDerivacion: lexyField({
      id: "pasoDerivacion",
      productDescription: "Paso actual dentro del subflujo de derivación.",
      dataType: "enum",
      enumValues: ["cliente", "recepcion", "acta", "cobro"],
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — acción principal"],
    }),
    pendienteConfirmacion: lexyField({
      id: "pendienteConfirmacion",
      productDescription:
        "Caso ya resuelto pero que sigue en 'En evaluación' esperando confirmación de nuevo cobro o reembolso.",
      dataType: "enum",
      enumValues: ["nuevo-cobro", "reembolso-baja"],
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    servicio: lexyField({
      id: "servicio",
      productDescription: "Servicio actual del cliente dentro de Lexy.",
      dataType: "enum",
      enumValues: ["Renegociación", "Liquidación", "Litigios/PP"],
      required: true,
      usage: {
        visible: true,
        editable: false,
        calculated: false,
        technical: false,
        filterable: true,
      },
      usedIn: [...usedInDesk, "Filtro por servicio"],
    }),
    servicioDestino: lexyField({
      id: "servicioDestino",
      productDescription: "Servicio al que se deriva el caso (subflujo Derivación).",
      dataType: "enum",
      enumValues: ["Renegociación", "Litigios", "Liquidación"],
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    etapaStreak: lexyField({
      id: "etapaStreak",
      productDescription: "Etapa del caso en Streak (CRM principal), según el servicio.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    motivo: lexyField({
      id: "motivo",
      productDescription: "Motivo de la reevaluación que originó el caso.",
      dataType: "enum",
      enumValues: ["Posible mal vendido", "Cambio de servicio", "Posible baja"],
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: [...usedInDesk, "Chip de motivo"],
    }),
    malVendidoCorresponde: {
      id: "malVendidoCorresponde",
      productDescription:
        "Si la capitana de ventas confirma que el caso corresponde a un posible mal vendido, al resolver un caso de reevaluación con motivo 'Posible mal vendido'.",
      dataType: "enum",
      enumValues: ["si", "no"],
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el subflujo de mal vendido (readme-logica-res.md §6 'Mal Vendido — eventos'). TI debe confirmar si esta revisión ya existe en el CRM de ventas o es exclusiva del Desk ReS.",
      ),
    },
    malVendidoJustificacion: {
      id: "malVendidoJustificacion",
      productDescription:
        "Justificación de la capitana de ventas de por qué corresponde o no corresponde mal vendido.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el subflujo de mal vendido. TI debe confirmar si esta revisión ya existe en el CRM de ventas o es exclusiva del Desk ReS.",
      ),
    },
    malVendidoCaminoSugerido: {
      id: "malVendidoCaminoSugerido",
      productDescription:
        "Camino que la capitana de ventas sugiere seguir con el caso cuando sí corresponde mal vendido. Es solo una sugerencia informativa para el capitán: no determina automáticamente el resultado de cierre.",
      dataType: "enum",
      enumValues: [
        "Mantener sin cambios",
        "Modificar estrategia en origen",
        "Derivar a otro servicio",
        "Dar de baja",
      ],
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el subflujo de mal vendido. TI debe confirmar si esta revisión ya existe en el CRM de ventas o es exclusiva del Desk ReS.",
      ),
    },
    motivoBaja: lexyField({
      id: "motivoBaja",
      productDescription: "Motivo específico de la baja, capturado al cerrar un caso como baja.",
      dataType: "enum",
      enumValues: [
        "Baja voluntaria",
        "Baja por no pago",
        "Baja por no colaborar",
        "Baja por derivación no aceptada o no completada",
      ],
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    comentarioBaja: {
      id: "comentarioBaja",
      productDescription:
        "Comentario de la decisión de baja: por qué se aprueba, por qué se rechaza, o qué información le falta pedir al capitán (mismo campo que usan tanto el paso 'Dar de baja' de DecisionCierreDialog como RevisionPosibleBajaDialog).",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el paso 'Dar de baja'. TI debe confirmar si ya existe un campo equivalente en el CRM.",
      ),
    },
    respuestaBaja: {
      id: "respuestaBaja",
      productDescription:
        "Respuesta del capitán al pedido de información de la líder de operaciones, en el vaivén de 'Posible baja' cuando falta información.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el vaivén líder/capitán de 'Posible baja'. TI debe confirmar si ya existe un campo equivalente en el CRM.",
      ),
    },
    turnoPosibleBaja: {
      id: "turnoPosibleBaja",
      productDescription:
        "De quién es el turno en el vaivén de 'Posible baja': la líder de operaciones decide (aprobar/rechazar/falta información) o el capitán completa la información que le pidieron.",
      dataType: "enum",
      enumValues: ["lider-operaciones", "capitan"],
      required: false,
      usage: { visible: false, editable: false, calculated: false, technical: true },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el vaivén líder/capitán de 'Posible baja'. TI debe confirmar si ya existe un campo equivalente en el CRM.",
      ),
    },
    rechazoRecepcionMotivo: {
      id: "rechazoRecepcionMotivo",
      productDescription:
        "Sugerencia de cómo seguir con el caso cuando el capitán receptor rechaza la derivación viendo el acta (derivar a otro equipo, dar de baja, u otro) — no es una decisión definitiva, el caso siempre se cierra igual y el capitán de origen decide el camino real por fuera de la app.",
      dataType: "enum",
      enumValues: ["Derivación a otro equipo", "Dar de baja", "Otro"],
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el rechazo de recepción de derivación. TI debe confirmar si ya existe un campo equivalente en el CRM.",
      ),
    },
    rechazoRecepcionJustificacion: {
      id: "rechazoRecepcionJustificacion",
      productDescription:
        "Justificación del capitán receptor de por qué rechaza la derivación y qué corresponde hacer con el caso.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el rechazo de recepción de derivación. TI debe confirmar si ya existe un campo equivalente en el CRM.",
      ),
    },
    origenPosibleBaja: {
      id: "origenPosibleBaja",
      productDescription:
        "Área o canal que origina la posible baja, capturado al crear un caso de reevaluación con motivo 'Posible baja'.",
      dataType: "enum",
      enumValues: ["Ventas", "Cobranza", "Cuotas impagas", "Ops", "Voluntaria"],
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el subflujo de posible baja. TI debe confirmar si esta clasificación de origen ya existe en el CRM o es exclusiva del Desk ReS.",
      ),
    },
    motivoPosibleBaja: {
      id: "motivoPosibleBaja",
      productDescription:
        "Motivo detallado de la posible baja (más granular que 'Tipo de baja'), capturado al crear un caso de reevaluación con motivo 'Posible baja'.",
      dataType: "enum",
      enumValues: [
        "1° cuota impaga",
        "2 cuotas impagas",
        "3 cuotas impagas",
        "4 cuotas impagas",
        "No colaboración",
        "Insatisfacción con el servicio",
        "Problemas económicos",
        "Mal vendido",
        "Inviable",
        "Venta arrepentida",
        "Inubicable",
      ],
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el subflujo de posible baja. TI debe confirmar si esta lista de motivos ya existe en el CRM o es exclusiva del Desk ReS.",
      ),
    },
    comentariosPosibleBaja: {
      id: "comentariosPosibleBaja",
      productDescription:
        "Comentarios libres sobre la posible baja, capturados al crear el caso para dar contexto a la líder de operaciones.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el subflujo de posible baja. TI debe confirmar si ya existe un campo equivalente en el CRM.",
      ),
    },
    motivoSolicitud: lexyField({
      id: "motivoSolicitud",
      productDescription: "Motivo informado para solicitar el reembolso.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    gestionesEquipo: lexyField({
      id: "gestionesEquipo",
      productDescription: "Gestiones realizadas por el equipo para evaluar el reembolso.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    motivoModificacionContrato: {
      id: "motivoModificacionContrato",
      productDescription:
        "Motivo por el que se modifica el contrato del cliente (incorporación de un nuevo acreedor, u otros).",
      dataType: "enum",
      enumValues: ["Agregar nuevo acreedor", "Otros"],
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para abrir el tipo de caso 'Modificación de contrato' en dos motivos. TI debe confirmar si esta clasificación existe en el CRM de origen o es exclusiva del Desk ReS.",
      ),
    },
    resultado: lexyField({
      id: "resultado",
      productDescription: "Resultado de cierre elegido al resolver el caso.",
      dataType: "enum",
      enumValues: [
        "Se mantiene",
        "Derivación a otro servicio",
        "Dar de baja",
        "Procede sin baja",
        "Procede con baja",
        "No procede",
        "Procede (nuevo cobro)",
      ],
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: [...usedInDesk, "Chip de resultado"],
    }),
    abogadoTramitador: lexyField({
      id: "abogadoTramitador",
      productDescription: "Abogado a cargo de tramitar el caso.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    abogadoVendedor: lexyField({
      id: "abogadoVendedor",
      productDescription: "Abogado que vendió el servicio original.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    capitanOrigen: lexyField({
      id: "capitanOrigen",
      productDescription: "Capitán del servicio de origen del caso.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    capitanACargo: lexyField({
      id: "capitanACargo",
      productDescription: "Capitán responsable de la gestión actual del caso.",
      dataType: "string",
      required: true,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    fechaGestion: lexyField({
      id: "fechaGestion",
      productDescription: "Plazo sugerido/asignado para resolver la gestión actual.",
      dataType: "date",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    notasEvaluacion: lexyField({
      id: "notasEvaluacion",
      productDescription: "Notas registradas al iniciar la evaluación del caso.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    descripcionVentas: lexyField({
      id: "descripcionVentas",
      productDescription:
        "Descripción precargada desde la caja post-venta (inmutable para el operador).",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
      note: NOTE_SCRAPER,
    }),
    estrategia: lexyField({
      id: "estrategia",
      productDescription:
        "Estrategia sugerida, precargada al crear el caso (contexto para quien genere un nuevo cobro por derivación, cuando aplica).",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
      note: NOTE_SCRAPER,
    }),
    tacticas: lexyField({
      id: "tacticas",
      productDescription:
        "Tácticas sugeridas, precargadas al crear el caso (contexto para quien genere un nuevo cobro por derivación, cuando aplica).",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
      note: NOTE_SCRAPER,
    }),
    cuotasSolicitadas: lexyField({
      id: "cuotasSolicitadas",
      productDescription:
        "Cuotas a reembolsar pedidas por el cliente al momento de la solicitud (texto libre: un número o 'A discusión').",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    montoReembolso: lexyField({
      id: "montoReembolso",
      productDescription: "Monto aprobado a reembolsar.",
      dataType: "number",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    cuotasReembolso: lexyField({
      id: "cuotasReembolso",
      productDescription: "Número de cuotas aprobado a reembolsar, decidido al resolver el caso.",
      dataType: "number",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    notaDevolucion: lexyField({
      id: "notaDevolucion",
      productDescription: "Nota registrada al aprobar el reembolso (con o sin baja).",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    motivoRechazoReembolso: lexyField({
      id: "motivoRechazoReembolso",
      productDescription: "Motivo por el que la solicitud de reembolso no procede.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    cuentaTitular: lexyField({
      id: "cuentaTitular",
      productDescription: "Titular de la cuenta bancaria para el depósito de reembolso.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
      sensitive: true,
    }),
    cuentaBanco: lexyField({
      id: "cuentaBanco",
      productDescription: "Banco de la cuenta para el depósito de reembolso.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
      sensitive: true,
    }),
    cuentaTipo: lexyField({
      id: "cuentaTipo",
      productDescription: "Tipo de cuenta bancaria (ej. Cuenta RUT, Cuenta Corriente).",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
      sensitive: true,
    }),
    cuentaNumero: lexyField({
      id: "cuentaNumero",
      productDescription: "Número de cuenta bancaria para el depósito de reembolso.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
      sensitive: true,
    }),
    reembolsoConfirmacionBajaEstado: lexyField({
      id: "reembolsoConfirmacionBajaEstado",
      productDescription: "Estado de la confirmación de depósito que cierra la baja con reembolso.",
      dataType: "enum",
      enumValues: ["pendiente", "confirmado"],
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    requiereAnalisisModificacionContrato: lexyField({
      id: "requiereAnalisisModificacionContrato",
      productDescription:
        "Si el capitán que deriva cree que el caso requiere análisis de modificación de contrato, marcado al llenar el acta de derivación. De ser así, antes de definir el nuevo cobro la capitana debe indicar si procede o no la modificación.",
      dataType: "boolean",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    modificacionContratoProcede: {
      id: "modificacionContratoProcede",
      productDescription:
        "Si la capitana confirma que procede la modificación de contrato, al resolver un caso de derivación que requiere este análisis. Si no procede, el caso igual queda derivado, sin nuevo cobro.",
      dataType: "enum",
      enumValues: ["si", "no"],
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el subflujo de análisis de modificación de contrato dentro de derivación. TI debe confirmar si esta revisión ya existe en el CRM de origen o es exclusiva del Desk ReS.",
      ),
    },
    modificacionContratoJustificacion: {
      id: "modificacionContratoJustificacion",
      productDescription:
        "Justificación de la capitana de por qué no procede la modificación de contrato.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInDesk,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Dato propuesto por usabilidad para el subflujo de análisis de modificación de contrato dentro de derivación. TI debe confirmar si esta revisión ya existe en el CRM de origen o es exclusiva del Desk ReS.",
      ),
    },
    detalleResolucion: lexyField({
      id: "detalleResolucion",
      productDescription: "Resumen de la resolución de cierre del caso.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    notaCierre: lexyField({
      id: "notaCierre",
      productDescription: "Nota final registrada al cerrar el caso.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    cerrado: lexyField({
      id: "cerrado",
      productDescription: "Si el caso está formalmente cerrado.",
      dataType: "boolean",
      required: true,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
    fechaRegistro: lexyField({
      id: "fechaRegistro",
      productDescription: "Fecha en que el caso se registró en el Desk ReS.",
      dataType: "date",
      required: true,
      usage: {
        visible: true,
        editable: false,
        calculated: false,
        technical: false,
        sortable: true,
      },
      usedIn: usedInDesk,
    }),
  },
};

const cliente: EntitySpec = {
  id: "cliente",
  productDescription: "Datos del cliente cuyo servicio se está reevaluando.",
  roleInExperience: "Dato del caso: el cliente no interactúa con la app, solo recibe correos.",
  usedIn: usedInDesk,
  origin: "lexyConfirmed",
  source: { kind: "unknown" },
  dataClassification: "sensitive",
  technicalValidation: pendingBackend(NOTE_SIN_BACKEND),
  fields: {
    nombre: lexyField({
      id: "nombre",
      productDescription: "Nombre del cliente.",
      dataType: "string",
      required: true,
      usage: {
        visible: true,
        editable: false,
        calculated: false,
        technical: false,
        filterable: true,
      },
      usedIn: [...usedInDesk, "Búsqueda por nombre"],
    }),
    correo: lexyField({
      id: "correo",
      productDescription: "Correo del cliente, usado para notificaciones automáticas.",
      dataType: "string",
      required: true,
      usage: {
        visible: true,
        editable: false,
        calculated: false,
        technical: false,
        filterable: true,
      },
      usedIn: [...usedInDesk, "Búsqueda por correo"],
      sensitive: true,
    }),
    telefono: lexyField({
      id: "telefono",
      productDescription: "Teléfono de contacto del cliente.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
      sensitive: true,
    }),
    idDefensoria: lexyField({
      id: "idDefensoria",
      productDescription: "ID Defensoría del cliente, mostrado en todas las tarjetas de caso.",
      dataType: "string",
      required: true,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: usedInDesk,
    }),
  },
};

const cobroAnterior: EntitySpec = {
  id: "cobroAnterior",
  productDescription:
    "Cobro vigente antes de la reevaluación, precargado desde la caja post-venta.",
  roleInExperience: "Contexto para decidir si el caso procede a reembolso, derivación o baja.",
  usedIn: ["Tarjeta de caso — cobro anterior (post- venta)"],
  origin: "lexyConfirmed",
  source: { kind: "unknown" },
  dataClassification: "internal",
  technicalValidation: pendingBackend(NOTE_SCRAPER),
  fields: {
    montoTotal: lexyField({
      id: "montoTotal",
      productDescription: "Monto total contratado en el cobro anterior (CLP).",
      dataType: "number",
      required: true,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — cobro anterior (post- venta)"],
      note: NOTE_SCRAPER,
    }),
    cuotas: lexyField({
      id: "cuotas",
      productDescription: "Número total de cuotas del cobro anterior.",
      dataType: "number",
      required: true,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — cobro anterior (post- venta)"],
      note: NOTE_SCRAPER,
    }),
    montoPrimeraCuota: lexyField({
      id: "montoPrimeraCuota",
      productDescription: "Monto de la primera cuota del cobro anterior.",
      dataType: "number",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — cobro anterior (post- venta)"],
      note: NOTE_SCRAPER,
    }),
    fechaInicio: lexyField({
      id: "fechaInicio",
      productDescription: "Fecha de inicio del cobro anterior.",
      dataType: "date",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — cobro anterior (post- venta)"],
      note: NOTE_SCRAPER,
    }),
    cuotasPagadas: lexyField({
      id: "cuotasPagadas",
      productDescription: "Cuántas cuotas del cobro anterior están pagadas.",
      dataType: "number",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — cobro anterior (post- venta)"],
      note: NOTE_SCRAPER,
    }),
    cuotasMorosas: lexyField({
      id: "cuotasMorosas",
      productDescription: "Cuántas cuotas del cobro anterior están en mora.",
      dataType: "number",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — cobro anterior (post- venta)"],
      note: NOTE_SCRAPER,
    }),
    pagoPrimeraCuota: lexyField({
      id: "pagoPrimeraCuota",
      productDescription: "Estado del pago de la primera cuota del cobro anterior.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — cobro anterior (post- venta)"],
      note: NOTE_SCRAPER,
    }),
  },
};

const usedInAcreedor = [
  "Tarjeta de caso — Acreedor",
  "Diálogo Nuevo caso — Agregar nuevo acreedor",
];

const acreedor: EntitySpec = {
  id: "acreedor",
  productDescription:
    "Acreedor externo que se incorpora al modificar el contrato del cliente (motivo 'Agregar nuevo acreedor').",
  roleInExperience: "Muestra la diferencia de deuda que justifica evaluar un nuevo cobro.",
  usedIn: usedInAcreedor,
  origin: "lexyConfirmed",
  source: { kind: "unknown" },
  dataClassification: "internal",
  technicalValidation: pendingBackend(NOTE_SCRAPER),
  fields: {
    nombre: {
      id: "nombre",
      productDescription: "Nombre del acreedor que se incorpora.",
      dataType: "string",
      required: true,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInAcreedor,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Hoy no existe scraper de acreedores: el nombre se captura a mano al crear el caso. TI debe confirmar si en producción se resuelve automáticamente.",
      ),
    },
    montoContratoActual: {
      id: "montoContratoActual",
      productDescription: "Monto del nuevo contrato con el acreedor.",
      dataType: "number",
      required: true,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInAcreedor,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Hoy no existe scraper de acreedores: el monto se captura a mano al crear el caso. TI debe confirmar si en producción se resuelve automáticamente.",
      ),
    },
    cuotas: {
      id: "cuotas",
      productDescription: "Número de cuotas del nuevo contrato con el acreedor.",
      dataType: "number",
      required: true,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInAcreedor,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Hoy no existe scraper de acreedores: el número de cuotas se captura a mano al crear el caso. TI debe confirmar si en producción se resuelve automáticamente.",
      ),
    },
    valorPrimeraCuota: {
      id: "valorPrimeraCuota",
      productDescription: "Valor de la primera cuota del nuevo contrato con el acreedor.",
      dataType: "number",
      required: true,
      usage: { visible: true, editable: true, calculated: false, technical: false },
      usedIn: usedInAcreedor,
      origin: "generatedByUsability",
      source: { kind: "unknown" },
      dataClassification: "internal",
      technicalValidation: pendingBackend(
        "Hoy no existe scraper de acreedores: el valor de la primera cuota se captura a mano al crear el caso. TI debe confirmar si en producción se resuelve automáticamente.",
      ),
    },
    diferencia: lexyField({
      id: "diferencia",
      productDescription: "Diferencia entre el monto del contrato actual y el cobro anterior.",
      dataType: "number",
      required: false,
      usage: { visible: true, editable: false, calculated: true, technical: false },
      usedIn: ["Tarjeta de caso — Acreedor"],
      derivation: "montoContratoActual − cobroAnterior.montoTotal (fórmula a confirmar con TI).",
    }),
  },
};

const actaDerivacion: EntitySpec = {
  id: "actaDerivacion",
  productDescription: "Acta que formaliza los términos de una derivación aceptada.",
  roleInExperience:
    "Registro que el capitán de origen completa al crear el caso de derivación; el capitán receptor la revisa para aceptar o rechazar, y quien genera el nuevo cobro la usa como contexto.",
  usedIn: usedInDesk,
  origin: "lexyConfirmed",
  source: { kind: "unknown" },
  dataClassification: "internal",
  technicalValidation: pendingBackend(NOTE_SIN_BACKEND),
  fields: (
    [
      ["abogadoVendedor", "Abogado que vendió el servicio original.", "string"],
      ["acreedores", "Acreedores vigentes del cliente al momento de derivar.", "string"],
      ["montoDeuda", "Monto total de deuda del cliente.", "number"],
      ["situacionTributaria", "Situación tributaria relevante del cliente.", "string"],
      ["demandas", "Demandas activas contra el cliente.", "string"],
      ["bienes", "Bienes del cliente relevantes para la derivación.", "string"],
      ["prendas", "Prendas vigentes sobre bienes del cliente.", "string"],
      ["hipotecario", "Situación hipotecaria del cliente.", "string"],
      ["pensionAlimentos", "Pensión de alimentos vigente, si aplica.", "string"],
      ["sociedades", "Sociedades en que participa el cliente.", "string"],
      [
        "otrosDatosImportantes",
        "Otros datos importantes que el capitán registra al derivar (finiquito, cuenta de ahorro, tramo de sueldo, herencia, etc.).",
        "string",
      ],
      ["resumen", "Resumen del caso para el servicio receptor.", "string"],
      ["compromisos", "Compromisos asumidos por el cliente al derivar.", "string"],
      [
        "derivacionAnteriorMotivo",
        "Motivo de la derivación anterior, cuando el cliente ya había sido derivado antes.",
        "string",
      ],
    ] as const
  ).reduce<Record<string, FieldSpec>>(
    (fields, [id, productDescription, dataType]) => {
      fields[id] = lexyField({
        id,
        productDescription,
        dataType,
        required: false,
        usage: { visible: true, editable: true, calculated: false, technical: false },
        usedIn: usedInDesk,
      });
      return fields;
    },
    {
      fechaPagoPrimeraCuota: lexyField({
        id: "fechaPagoPrimeraCuota",
        productDescription: "Fecha comprometida de pago de la primera cuota del nuevo cobro.",
        dataType: "date",
        required: false,
        usage: { visible: true, editable: true, calculated: false, technical: false },
        usedIn: usedInDesk,
      }),
      huboDerivacionAnterior: lexyField({
        id: "huboDerivacionAnterior",
        productDescription:
          "Si el cliente ya había sido derivado antes de este caso ('Derivaciones realizadas' en el acta; por defecto 'Ninguna').",
        dataType: "boolean",
        required: false,
        usage: { visible: true, editable: true, calculated: false, technical: false },
        usedIn: usedInDesk,
      }),
      derivacionAnteriorServicio: lexyField({
        id: "derivacionAnteriorServicio",
        productDescription: "Servicio desde el que se derivó al cliente la vez anterior.",
        dataType: "enum",
        enumValues: ["Renegociación", "Litigios", "Liquidación"],
        required: false,
        usage: { visible: true, editable: true, calculated: false, technical: false },
        usedIn: usedInDesk,
      }),
      servicioTentativo: lexyField({
        id: "servicioTentativo",
        productDescription:
          "Servicio propuesto antes de que exista acta (detalle de la derivación).",
        dataType: "string",
        required: false,
        usage: { visible: true, editable: false, calculated: false, technical: false },
        usedIn: ["Tarjeta de caso — Detalle de la derivación"],
      }),
      solicitadoPor: lexyField({
        id: "solicitadoPor",
        productDescription: "Quién solicitó la derivación.",
        dataType: "string",
        required: false,
        usage: { visible: true, editable: false, calculated: false, technical: false },
        usedIn: ["Tarjeta de caso — Detalle de la derivación"],
      }),
      justificacion: lexyField({
        id: "justificacion",
        productDescription: "Justificación de por qué se propone derivar el caso.",
        dataType: "string",
        required: false,
        usage: { visible: true, editable: false, calculated: false, technical: false },
        usedIn: ["Tarjeta de caso — Detalle de la derivación"],
      }),
    },
  ),
};

const nuevoCobro: EntitySpec = {
  id: "nuevoCobro",
  productDescription: "Nuevo cobro que se genera en Apio cuando la derivación lo requiere.",
  roleInExperience: "Seguimiento del cobro hasta que el cliente lo acepta en Apio.",
  usedIn: ["Tarjeta de caso — Nuevo cobro"],
  origin: "lexyConfirmed",
  source: { kind: "unknown" },
  dataClassification: "internal",
  technicalValidation: pendingBackend(NOTE_APIO),
  fields: {
    estado: lexyField({
      id: "estado",
      productDescription: "Estado del nuevo cobro en su ciclo de vida.",
      dataType: "enum",
      enumValues: [
        "pendiente",
        "no-aplica",
        "definido",
        "confirmado",
        "esperando-cliente",
        "aceptado-cliente",
      ],
      required: true,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — Nuevo cobro"],
      note: NOTE_APIO,
    }),
    aplica: lexyField({
      id: "aplica",
      productDescription: "Si la derivación efectivamente requiere un nuevo cobro.",
      dataType: "boolean",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — Nuevo cobro"],
    }),
    motivoNoAplica: lexyField({
      id: "motivoNoAplica",
      productDescription: "Motivo por el que no aplica un nuevo cobro.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — Nuevo cobro"],
    }),
    valor: lexyField({
      id: "valor",
      productDescription: "Valor del nuevo cobro (CLP).",
      dataType: "number",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — Nuevo cobro"],
      note: NOTE_APIO,
    }),
    cuotas: lexyField({
      id: "cuotas",
      productDescription: "Número de cuotas del nuevo cobro.",
      dataType: "number",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — Nuevo cobro"],
      note: NOTE_APIO,
    }),
    observaciones: lexyField({
      id: "observaciones",
      productDescription: "Observaciones sobre el nuevo cobro.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — Nuevo cobro"],
    }),
    confirmadoPor: lexyField({
      id: "confirmadoPor",
      productDescription: "Quién confirmó el nuevo cobro.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — Nuevo cobro"],
    }),
    fechaDefinicion: lexyField({
      id: "fechaDefinicion",
      productDescription: "Fecha en que se definió el nuevo cobro.",
      dataType: "date",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — Nuevo cobro"],
    }),
    fechaConfirmacion: lexyField({
      id: "fechaConfirmacion",
      productDescription: "Fecha en que el cliente aceptó el cobro en Apio.",
      dataType: "date",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — Nuevo cobro"],
      note: NOTE_APIO,
    }),
  },
};

const documento: EntitySpec = {
  id: "documento",
  productDescription: "Documento adjunto a un caso (comprobantes, actas escaneadas, etc.).",
  roleInExperience: "Evidencia de respaldo consultable desde la ficha del caso.",
  usedIn: [
    "Tarjeta de caso — Documentos adjuntos",
    "Diálogo Confirmar depósito — comprobante de depósito",
  ],
  origin: "lexyConfirmed",
  source: { kind: "unknown" },
  dataClassification: "internal",
  technicalValidation: pendingBackend(NOTE_SIN_BACKEND),
  fields: {
    nombre: lexyField({
      id: "nombre",
      productDescription: "Nombre del documento.",
      dataType: "string",
      required: true,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: [
        "Tarjeta de caso — Documentos adjuntos",
        "Diálogo Confirmar depósito — comprobante de depósito",
      ],
    }),
    tipo: lexyField({
      id: "tipo",
      productDescription: "Tipo de archivo del documento.",
      dataType: "enum",
      enumValues: ["pdf", "word", "imagen"],
      required: true,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: [
        "Tarjeta de caso — Documentos adjuntos",
        "Diálogo Confirmar depósito — comprobante de depósito",
      ],
    }),
    url: lexyField({
      id: "url",
      productDescription: "Enlace de descarga o vista del documento.",
      dataType: "string",
      required: true,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: [
        "Tarjeta de caso — Documentos adjuntos",
        "Diálogo Confirmar depósito — comprobante de depósito",
      ],
    }),
  },
};

const gestion: EntitySpec = {
  id: "gestion",
  productDescription: "Registro de una gestión realizada sobre el caso.",
  roleInExperience: "Historial de seguimiento visible en la ficha del caso.",
  usedIn: ["Tarjeta de caso — Gestiones realizadas"],
  origin: "lexyConfirmed",
  source: { kind: "unknown" },
  dataClassification: "internal",
  technicalValidation: pendingBackend(NOTE_SIN_BACKEND),
  fields: {
    capitan: lexyField({
      id: "capitan",
      productDescription: "Capitán que realizó la gestión.",
      dataType: "string",
      required: true,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — Gestiones realizadas"],
    }),
    fecha: lexyField({
      id: "fecha",
      productDescription: "Fecha en que se realizó la gestión.",
      dataType: "date",
      required: true,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — Gestiones realizadas"],
    }),
    nota: lexyField({
      id: "nota",
      productDescription: "Nota registrada sobre la gestión.",
      dataType: "string",
      required: false,
      usage: { visible: true, editable: false, calculated: false, technical: false },
      usedIn: ["Tarjeta de caso — Gestiones realizadas"],
    }),
  },
};

const embeddedRelation = (
  id: string,
  toEntity: string,
  cardinality: RelationSpec["cardinality"],
  productDescription: string,
): RelationSpec => ({
  id,
  fromEntity: "caso",
  toEntity,
  cardinality,
  productDescription,
  requiredBy: usedInDesk,
  resolution: "embedded",
  origin: "lexyConfirmed",
  source: { kind: "unknown" },
  dataClassification: "internal",
  technicalValidation: pendingBackend(NOTE_SIN_BACKEND),
});

export const prototypeDataContract = definePrototypeDataContract({
  contractVersion: "1",
  project: {
    name: "deskres",
    description:
      "Desk ReS: gestor interno de reevaluación de servicio (mantener, derivar o dar de baja un caso).",
  },
  entities: {
    caso,
    cliente,
    cobroAnterior,
    acreedor,
    actaDerivacion,
    nuevoCobro,
    documento,
    gestion,
  },
  relations: [
    embeddedRelation("casoCliente", "cliente", "oneToOne", "Cada caso tiene un cliente."),
    embeddedRelation(
      "casoCobroAnterior",
      "cobroAnterior",
      "oneToOne",
      "El caso puede traer el cobro vigente antes de la reevaluación.",
    ),
    embeddedRelation(
      "casoAcreedor",
      "acreedor",
      "oneToOne",
      "El caso puede estar vinculado a un acreedor externo.",
    ),
    embeddedRelation(
      "casoActaDerivacion",
      "actaDerivacion",
      "oneToOne",
      "El caso puede tener un acta de derivación una vez que el cliente acepta evaluar.",
    ),
    embeddedRelation(
      "casoNuevoCobro",
      "nuevoCobro",
      "oneToOne",
      "El caso puede requerir un nuevo cobro cuando se deriva a otro servicio.",
    ),
    embeddedRelation(
      "casoDocumentos",
      "documento",
      "oneToMany",
      "El caso puede tener documentos adjuntos.",
    ),
    embeddedRelation(
      "casoGestiones",
      "gestion",
      "oneToMany",
      "El caso acumula un historial de gestiones realizadas.",
    ),
  ],
});
